server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - http://localhost:5173
            - http://localhost:5000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: "http://localhost:8088/reamls/demo"

#

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#     defaultZone: http://eureka-server:8761/eureka for docker
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true


# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


application:
  security:
    jwt:
      secret-key: bb49931b1b6e4cd6529c2f21bcbce342c46d5dfe6b8b829237dceff8afb4d1cf