server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
#        - id:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#     defaultZone: http://eureka-server:8761/eureka for docker
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true


# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


application:
  security:
    jwt:
      secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxNDA0OTI2OSwiaWF0IjoxNzE0MDQ5MjY5fQ.AUTscBS7TFPgTd2prOAJIY3Duxh0wFEm-3I1J0HEwyE