server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

#

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
#     defaultZone: http://eureka-server:8761/eureka for docker
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true


# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


application:
  security:
    jwt:
      secret-key: bb49931b1b6e4cd6529c2f21bcbce342c46d5dfe6b8b829237dceff8afb4d1cf