server:
  port: 8081

spring:
  application:
    name: user-service
  #    database
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://localhost:5432/user
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  rabbitmq:
    addresses: localhost:5672

#eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka-server:8761/eureka for docker

# tracing

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true




# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

rabbitmq:
  exchanges:
    internal: internal.exchanges
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-keys