server:
  port: 8086
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: admin
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  flyway:
    locations: classpath:/db/migration

#  rabbitmq:
#    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #      defaultZone: http://eureka-server:8761/eureka for docker

# tracing
# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true

# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        security: DEBUG


